name: Roger Shaw
favicon: null
layout_spectrum: 0.8959690767806023
typography_spectrum: 0.04861965915188193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5826262289192528
  lightness: 0.0658927105832845
  saturation: 0.12384130666032434
  rhythmicContrast: 0.9527668172959238
purpose: []
